### ISSUE TITLE
Use builders instead of models

### ISSUE THREAD

**Issue by andrewkhan1** [huntie/laravel-simple-jsonapi#11]
Hi Alex, hope you're doing well :)

This is awesome, I have just completed something very similar at TJC

A few things I picked up which may help you...
1. Base REST response generation on builders vs models (basing it on models is very very restrictive, alternatively you could allow both to be passed)
2. Abstract out response generation to a separate package and make sure it's framework agnostic (this way you can reuse the same system in any code base - reuse <3). 
3. Reuse by composition is almost always better than inheritance (granted this is personal preference). Generally I find reuse by inheritance hard to read and also since PHP can't do multiple inheritance you are restricting people using base controllers

Good luck it's looking good :)

**Comment by huntie** [comment]
Hey Andrew, managed to miss seeing this until today! So happy that you've taken a look through the project :)

In response to your suggestions:
1. Response generation is generally based on Models, as right now they provide all the information required to correctly generate a JSON API Resource Object, such as attribute type casting and behaviours set by the developer, and also relationship definitions. Before this point, it's entirely possible to retrieve the target record(s) using a `Builder` in an overridden controller method (though a better interface in the future would be nice). Perhaps I'm missing a trick, but `Model` appears adequate for now. Notably, `CollectionSerializer` does accept a `Builder` or `LengthAwarePaginator`, as needed to get query information for the response.
2. I recently completed a refactor of response generation into dedicated `Serializer` classes which should be a more direct abstraction – however indeed they remain quite tightly coupled to Laravel's `Model` class. The spirit of the library right now is to require next to no configuration within Laravel, however that does not prevent framework agnostic components being mapped to internally, so eventually that would be great.
3. Agreed, inheritance can get restrictive – I expect you're primarily referring to `JsonApiController`. The hardest thing to get working at the start of this project was providing an extended `Controller` with preset, but overridable methods (parameters have to match in extended PHP classes :|), and the combination of a base controller and a trait (for which inherited methods can be overwritten) was one of the only approaches. Will take a second look at the composition pattern and see if it can improve any area of the codebase.

I'm definitely taking every point on board, and it should be easier to make changes once I have test coverage up too, which is my immediate objective when I next get a chance to code, and will mark an initial release version. Thanks for the pointers :)

**Comment by andrewkhan1** [comment]
1. True - but you can use `$builder->getModel()` to retrieve the information you need. The benefit of using a builder is that query parameters can be applied before generating the response, whereas using a model means you can only ever return basic queries. 
2. You can use interfaces and service providers to define a default implementation
3. Definitely, I don't think there's a perfect solution to this. 

Good luck and hope you're doing well :)
